"""Training entry-point for the seismic CNN-1D model.

Fast path: if data/processed/train.npz, val.npz, test.npz exist (generated by
scripts/prepare_dataset.py), they are loaded directly — no raw data parsing.

Slow path: if .npz files are missing, raw STEAD + Phyphox files are loaded
and balanced on-the-fly according to training_config.yaml settings.
"""

import os
import sys
from pathlib import Path
from typing import Tuple

import numpy as np
import tensorflow as tf
import yaml

sys.path.insert(0, str(Path(__file__).parent))

from data_loader import SeismicDataGenerator, create_train_val_test_split
from model import build_model

CONFIG_PATH = Path(__file__).parents[1] / "configs" / "training_config.yaml"
MODEL_DIR = Path(__file__).parents[1] / "models"


def load_config(path: Path) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def _load_npz_as_generator(
    npz_path: Path, batch_size: int, augment: bool, shuffle: bool
) -> SeismicDataGenerator:
    """Load a preprocessed .npz split into a SeismicDataGenerator."""
    d = np.load(npz_path)
    X = d["X"]  # shape (N, 1000, 6)
    n = len(X)

    samples = []
    for i in range(n):
        label = {
            "is_earthquake": np.array([d["is_earthquake"][i]], dtype=np.float32),
            "intensity": int(d["intensity"][i]),
            "pga": np.array([d["pga"][i]], dtype=np.float32),
            "dominant_freq": np.array([d["dominant_freq"][i]], dtype=np.float32),
            "duration": np.array([d["duration"][i]], dtype=np.float32),
        }
        samples.append((X[i], label))

    return SeismicDataGenerator(samples, batch_size=batch_size, augment=augment, shuffle=shuffle)


def load_generators(
    cfg: dict,
) -> Tuple[SeismicDataGenerator, SeismicDataGenerator, SeismicDataGenerator]:
    """Return (train_gen, val_gen, test_gen) from either .npz or raw data."""
    t = cfg["training"]
    d = cfg["data"]
    repo_root = Path(__file__).parents[2]
    processed_dir = repo_root / d["processed_dir"]
    batch_size = t["batch_size"]

    train_npz = processed_dir / "train.npz"
    val_npz = processed_dir / "val.npz"
    test_npz = processed_dir / "test.npz"

    if train_npz.exists() and val_npz.exists() and test_npz.exists():
        print(f"Loading preprocessed dataset from {processed_dir}")
        train_gen = _load_npz_as_generator(train_npz, batch_size, augment=True, shuffle=True)
        val_gen = _load_npz_as_generator(val_npz, batch_size, augment=False, shuffle=False)
        test_gen = _load_npz_as_generator(test_npz, batch_size, augment=False, shuffle=False)
        print(f"  train={len(train_gen.samples)}  val={len(val_gen.samples)}  test={len(test_gen.samples)}")
        return train_gen, val_gen, test_gen

    # Fall back to raw data loading
    print("Preprocessed .npz not found — loading raw data (run scripts/prepare_dataset.py first for speed)")

    stead_dir = repo_root / d["stead_dir"]
    phyphox_dir = repo_root / d["phyphox_dir"]

    stead_paths = sorted(stead_dir.glob("*.hdf5")) + sorted(stead_dir.glob("*.h5"))
    if not stead_paths:
        print(f"[ERROR] No STEAD files in {stead_dir}")
        sys.exit(1)

    return create_train_val_test_split(
        stead_paths=[str(p) for p in stead_paths],
        phyphox_root=str(phyphox_dir),
        val_ratio=d["val_ratio"],
        test_ratio=d["test_ratio"],
        batch_size=batch_size,
        balance_stead_to_phyphox=d.get("balance_stead_to_phyphox", True),
        seed=d.get("random_seed", 42),
    )


def build_compiled_model(cfg: dict) -> tf.keras.Model:
    model = build_model()
    lw = cfg["training"]["loss_weights"]
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=cfg["training"]["learning_rate"]),
        loss={
            "is_earthquake": tf.keras.losses.BinaryCrossentropy(),
            "intensity": tf.keras.losses.CategoricalCrossentropy(),
            "pga": tf.keras.losses.MeanAbsoluteError(),
            "dominant_freq": tf.keras.losses.MeanAbsoluteError(),
            "duration": tf.keras.losses.MeanAbsoluteError(),
        },
        loss_weights=lw,
        metrics={
            "is_earthquake": [tf.keras.metrics.AUC(name="auc"), "accuracy"],
            "intensity": ["accuracy"],
            "pga": [tf.keras.metrics.MeanAbsoluteError(name="mae")],
            "dominant_freq": [tf.keras.metrics.MeanAbsoluteError(name="mae")],
            "duration": [tf.keras.metrics.MeanAbsoluteError(name="mae")],
        },
    )
    return model


def main() -> None:
    cfg = load_config(CONFIG_PATH)
    t = cfg["training"]
    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    best_model_path = MODEL_DIR / "best_model.keras"

    train_gen, val_gen, _ = load_generators(cfg)

    model = build_compiled_model(cfg)
    model.summary()

    callbacks = [
        tf.keras.callbacks.EarlyStopping(
            monitor="val_loss",
            patience=t["early_stopping_patience"],
            restore_best_weights=True,
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss", factor=0.5, patience=5, min_lr=1e-6, verbose=1
        ),
        tf.keras.callbacks.ModelCheckpoint(
            filepath=str(best_model_path),
            monitor="val_loss",
            save_best_only=True,
            verbose=1,
        ),
    ]

    history = model.fit(
        train_gen,
        validation_data=val_gen,
        epochs=t["epochs"],
        callbacks=callbacks,
    )

    best_epoch = int(tf.argmin(history.history["val_loss"]).numpy())
    best_val_loss = history.history["val_loss"][best_epoch]
    print("\n=== Training Summary ===")
    print(f"Best epoch    : {best_epoch + 1}")
    print(f"Best val_loss : {best_val_loss:.4f}")
    print(f"Model saved   : {best_model_path}")


if __name__ == "__main__":
    main()
